language: java

install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify -Dgpg.skip=true -B

jdk:
  - oraclejdk9
  - openjdk9

cache:
  directories:
    - $HOME/.m2
